- name: Install zsh
  apt: name=zsh
- name: Install fontconfig
  apt: name=fontconfig
- name: Change fontconfig
  shell: fc-cache -fv
- name: Change SHELL
  shell: chsh -s `which zsh`
- name: Install OhMyZSH
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
- name: Install zsh autosuggesions plugin
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ lookup('env', 'ZSH_CUSTOM') }}/plugins/zsh-autosuggestions"
- name: Install zsh syntax highlighting plugin
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ lookup('env', 'ZSH_CUSTOM') }}/plugins/zsh-autosuggestions"
- name: Install zsh themes
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "{{ lookup('env', 'ZSH_CUSTOM') }}/themes/powerlevel10k"
